-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_GameState" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "paperclips" REAL NOT NULL DEFAULT 0,
    "money" REAL NOT NULL DEFAULT 0,
    "wire" REAL NOT NULL DEFAULT 1000,
    "yomi" REAL NOT NULL DEFAULT 0,
    "autoclippers" INTEGER NOT NULL DEFAULT 0,
    "autoclipper_cost" REAL NOT NULL DEFAULT 10,
    "clicks_per_second" REAL NOT NULL DEFAULT 0,
    "clickMultiplier" INTEGER NOT NULL DEFAULT 1,
    "totalClicks" INTEGER NOT NULL DEFAULT 0,
    "totalPaperclipsMade" REAL NOT NULL DEFAULT 0,
    "revenuePerSecond" REAL NOT NULL DEFAULT 0,
    "productionMultiplier" REAL NOT NULL DEFAULT 1,
    "megaClippers" INTEGER NOT NULL DEFAULT 0,
    "megaClipperCost" REAL NOT NULL DEFAULT 5000,
    "megaClippersUnlocked" BOOLEAN NOT NULL DEFAULT false,
    "spoolCost" REAL NOT NULL DEFAULT 5,
    "wirePerSpool" REAL NOT NULL DEFAULT 1000,
    "autoWireBuyer" BOOLEAN NOT NULL DEFAULT false,
    "autoWireBuyerCost" REAL NOT NULL DEFAULT 100,
    "spoolSizeUpgradeCost" REAL NOT NULL DEFAULT 125,
    "spoolSizeLevel" INTEGER NOT NULL DEFAULT 1,
    "lastWirePurchaseTime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "wirePurchaseCount" INTEGER NOT NULL DEFAULT 0,
    "paperclipPrice" REAL NOT NULL DEFAULT 0.25,
    "marketDemand" REAL NOT NULL DEFAULT 10,
    "paperclipsSold" REAL NOT NULL DEFAULT 0,
    "totalSales" REAL NOT NULL DEFAULT 0,
    "basePaperclipPrice" REAL NOT NULL DEFAULT 0.25,
    "elasticity" REAL NOT NULL DEFAULT 3,
    "marketTrend" REAL NOT NULL DEFAULT 0,
    "seasonalMultiplier" REAL NOT NULL DEFAULT 1,
    "volatility" REAL NOT NULL DEFAULT 0.15,
    "maxDemand" REAL NOT NULL DEFAULT 50,
    "minDemand" REAL NOT NULL DEFAULT 1,
    "marketDemandLevel" INTEGER NOT NULL DEFAULT 1,
    "marketDemandUpgradeCost" REAL NOT NULL DEFAULT 200,
    "marketingLevel" INTEGER NOT NULL DEFAULT 0,
    "marketingCost" REAL NOT NULL DEFAULT 200,
    "demandMultiplier" REAL NOT NULL DEFAULT 1.0,
    "researchPoints" REAL NOT NULL DEFAULT 0,
    "researchPointsPerSecond" REAL NOT NULL DEFAULT 0.5,
    "unlockedResearch" TEXT NOT NULL DEFAULT '[]',
    "stockMarketUnlocked" BOOLEAN NOT NULL DEFAULT false,
    "tradingBots" INTEGER NOT NULL DEFAULT 0,
    "tradingBotCost" REAL NOT NULL DEFAULT 1000,
    "botIntelligence" INTEGER NOT NULL DEFAULT 1,
    "botIntelligenceCost" REAL NOT NULL DEFAULT 1500,
    "botTradingBudget" REAL NOT NULL DEFAULT 0,
    "botLastTradeTime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "botTradingProfit" REAL NOT NULL DEFAULT 0,
    "botTradingLosses" REAL NOT NULL DEFAULT 0,
    "stockMarketReturns" REAL NOT NULL DEFAULT 0,
    "stockMarketInvestment" REAL NOT NULL DEFAULT 0,
    "stockMarketLastUpdate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "stockPortfolio" TEXT NOT NULL DEFAULT '[]',
    "stockPriceHistory" TEXT NOT NULL DEFAULT '{}',
    "portfolioValue" REAL NOT NULL DEFAULT 0,
    "cpuLevel" INTEGER NOT NULL DEFAULT 1,
    "cpuCost" REAL NOT NULL DEFAULT 100,
    "memory" REAL NOT NULL DEFAULT 1,
    "memoryMax" REAL NOT NULL DEFAULT 1,
    "memoryCost" REAL NOT NULL DEFAULT 100,
    "memoryRegenRate" REAL NOT NULL DEFAULT 1,
    "trust" REAL NOT NULL DEFAULT 0,
    "trustLevel" INTEGER NOT NULL DEFAULT 0,
    "nextTrustAt" REAL NOT NULL DEFAULT 100000,
    "ops" REAL NOT NULL DEFAULT 10,
    "opsMax" REAL NOT NULL DEFAULT 10,
    "creativity" REAL NOT NULL DEFAULT 0,
    "creativityUnlocked" BOOLEAN NOT NULL DEFAULT false,
    "unlockedOpsUpgrades" TEXT NOT NULL DEFAULT '[]',
    "unlockedCreativityUpgrades" TEXT NOT NULL DEFAULT '[]',
    "metricsUnlocked" BOOLEAN NOT NULL DEFAULT false,
    "lastSaved" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastPriceUpdate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "GameState_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_GameState" ("autoWireBuyer", "autoWireBuyerCost", "autoclipper_cost", "autoclippers", "basePaperclipPrice", "botIntelligence", "botIntelligenceCost", "botLastTradeTime", "botTradingBudget", "botTradingLosses", "botTradingProfit", "clickMultiplier", "clicks_per_second", "cpuCost", "cpuLevel", "creativity", "creativityUnlocked", "demandMultiplier", "elasticity", "id", "lastPriceUpdate", "lastSaved", "lastWirePurchaseTime", "marketDemand", "marketDemandLevel", "marketDemandUpgradeCost", "marketTrend", "marketingCost", "marketingLevel", "maxDemand", "megaClipperCost", "megaClippers", "megaClippersUnlocked", "memory", "memoryCost", "memoryMax", "memoryRegenRate", "metricsUnlocked", "minDemand", "money", "nextTrustAt", "ops", "opsMax", "paperclipPrice", "paperclips", "paperclipsSold", "portfolioValue", "productionMultiplier", "researchPoints", "researchPointsPerSecond", "revenuePerSecond", "seasonalMultiplier", "spoolCost", "spoolSizeLevel", "spoolSizeUpgradeCost", "stockMarketInvestment", "stockMarketLastUpdate", "stockMarketReturns", "stockMarketUnlocked", "stockPortfolio", "stockPriceHistory", "totalClicks", "totalPaperclipsMade", "totalSales", "tradingBotCost", "tradingBots", "trust", "trustLevel", "unlockedCreativityUpgrades", "unlockedOpsUpgrades", "unlockedResearch", "userId", "volatility", "wire", "wirePerSpool", "wirePurchaseCount") SELECT "autoWireBuyer", "autoWireBuyerCost", "autoclipper_cost", "autoclippers", "basePaperclipPrice", "botIntelligence", "botIntelligenceCost", "botLastTradeTime", "botTradingBudget", "botTradingLosses", "botTradingProfit", "clickMultiplier", "clicks_per_second", "cpuCost", "cpuLevel", "creativity", "creativityUnlocked", "demandMultiplier", "elasticity", "id", "lastPriceUpdate", "lastSaved", "lastWirePurchaseTime", "marketDemand", "marketDemandLevel", "marketDemandUpgradeCost", "marketTrend", "marketingCost", "marketingLevel", "maxDemand", "megaClipperCost", "megaClippers", "megaClippersUnlocked", "memory", "memoryCost", "memoryMax", "memoryRegenRate", "metricsUnlocked", "minDemand", "money", "nextTrustAt", "ops", "opsMax", "paperclipPrice", "paperclips", "paperclipsSold", "portfolioValue", "productionMultiplier", "researchPoints", "researchPointsPerSecond", "revenuePerSecond", "seasonalMultiplier", "spoolCost", "spoolSizeLevel", "spoolSizeUpgradeCost", "stockMarketInvestment", "stockMarketLastUpdate", "stockMarketReturns", "stockMarketUnlocked", "stockPortfolio", "stockPriceHistory", "totalClicks", "totalPaperclipsMade", "totalSales", "tradingBotCost", "tradingBots", "trust", "trustLevel", "unlockedCreativityUpgrades", "unlockedOpsUpgrades", "unlockedResearch", "userId", "volatility", "wire", "wirePerSpool", "wirePurchaseCount" FROM "GameState";
DROP TABLE "GameState";
ALTER TABLE "new_GameState" RENAME TO "GameState";
CREATE UNIQUE INDEX "GameState_userId_key" ON "GameState"("userId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
